version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: diarias
      POSTGRES_USER: diarias
      POSTGRES_PASSWORD: diarias
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U diarias -d diarias"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgres://diarias:diarias@db:5432/diarias
      ORIGEM_UF: CE
      PORT: 3333
    ports: ["3333:3333"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  web:
    build:
      context: .
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
      PORT: 3000
    ports: ["3000:3000"]
    depends_on:
      - api

volumes:
  db_data:
